services:

  client:
    build: ./client
    image: erckafrmns/atkk-client:v1.1
    volumes:
      - ./client:/client-app
    ports:
      - "3000:80"  
    depends_on:
      - server

  server:
    build: ./server
    image: erckafrmns/atkk-server:v1.1
    volumes:
      - ./server:/server-app
    ports:
      - "5000:5000"  
    depends_on:
      - model
      - db 
    env_file:
      - .env
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

  model:
    build: ./model
    image: erckafrmns/atkk-model:v1.1
    volumes:
      - ./model:/model-app
    ports:
      - "5001:5001"
    environment:
      - MODEL_PATH=/model-app/trained_model

  db:
    image: postgres:17.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}  
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DB=${POSTGRES_DB} 
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "5432:5432"  

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:  
