services:

  client:
    build: ./client
    volumes:
      - ./client:/client-app
    ports:
      - "3000:80"  
    depends_on:
      - server

  server:
    build: ./server
    volumes:
      - ./server:/server-app
    ports:
      - "5000:5000"  
    depends_on:
      - model
      - db 
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:admin@db:5432/ATKK_DB

  model:
    build: ./model
    volumes:
      - ./model:/model-app
    ports:
      - "5001:5001"
    environment:
      - MODEL_PATH=/model-app/trained_model

  db:
    image: postgres:17.1
    environment:
      - POSTGRES_USER=postgres  
      - POSTGRES_PASSWORD=admin  
      - POSTGRES_DB=ATKK_DB 
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "5432:5432"  

volumes:
  postgres_data:  
