from flask import Flask, request, jsonify, make_response
from flask_sqlalchemy import SQLAlchemy
from os import environ
from flask_cors import CORS
import psycopg2

app = Flask(__name__)
CORS(app)

@app.route("/users")
def users():
    return {"users": ["Ericka", "Grace", "Ernest", "Pao","Nino"]}


# Database connection
# def get_db_connection():
#     conn = psycopg2.connect(
#         host="localhost",
#         database="ATKK_DB",
#         user="postgres",
#         password="admin"
#     )
#     return conn


# @app.route('/generate_story', methods=['POST'])
# def generate_story():
#     data = request.get_json()
#     # Call your AI model here
#     story = {
#         "title": "Sample Story",
#         "content": "This is a sample story generated by the AI."
#     }
#     return jsonify(story)

# @app.route('/history', methods=['GET'])
# def get_history():
#     conn = get_db_connection()
#     cur = conn.cursor()
#     cur.execute("SELECT * FROM stories;")  # Adjust to your stories table structure
#     stories = cur.fetchall()
#     cur.close()
#     conn.close()
#     return jsonify(stories)

if __name__ == "__main__":
    app.run(debug=True)
